### ISSUE TITLE
Utop (opam version) failing to run on nixos 

### ISSUE THREAD

**Issue by rand00** [ocaml-community/utop#109]
The utop package was downloaded through opam 1.1.1. 

When running utop in the terminal the following error emerges:

```
*** Error in `/home/rand/.opam/4.02.1/bin/utop': double free or corruption (out): 0x000000000064c920 ***
Aborted
```

**Comment by rhacker** [comment]
I have the same problem running gcc

**Comment by whitequark** [comment]
This seems to be fixed in master opam.
