### ISSUE TITLE
utop in emacs

### ISSUE THREAD

**Issue by monadbobo** [ocaml-community/utop#12]
My os is MAC 10.7.5 and emacs version is 24.3.

I add follow line to my emacs config(.emacs):

(load-file "~/.opam/system/share/emacs/site-lisp/utop.el")
(autoload 'utop "utop" "Toplevel for OCaml" t)
(autoload 'utop-setup-ocaml-buffer "utop" "Toplevel for OCaml" t)
(add-hook 'tuareg-mode-hook 'utop-setup-ocaml-buffer)
(add-hook 'typerex-mode-hook 'utop-setup-ocaml-buffer)

and run utop in emacs , and then output 

Process utop exited with code 2

but i run utop in my terminal , everything is ok.

Thanks.

**Comment by Blaisorblade** [comment]
I needed to use `(setq utop-command "/usr/local/bin/opam config exec -- utop -emacs")`.

First I tried `(setq utop-command "opam config exec \"utop -emacs\"")`, but that didn't work (plus, `opam config --help` documents the latter syntax, not the former).

**Comment by Blaisorblade** [comment]
More importantly: I don't see documentation with this suggestion. Could this be added to the https://github.com/diml/utop/blob/master/README.md?

**Comment by diml** [comment]
Sure, I updated the README
