### ISSUE TITLE
autoload failed to define function utop-minor-mode

### ISSUE THREAD

**Issue by bgrange** [ocaml-community/utop#127]
I'm getting this error when I try to run utop-minor-mode in emacs.  I'm suspecting this is because I have release 1.17 and minor mode was added since that release.  Is this true?

**Comment by diml** [comment]
Yes, indeed the README on github is not in sync with the latest release... We'll do a release soon to fix that

**Comment by itegebo** [comment]
+1 Just bumped into this as well.

**Comment by diml** [comment]
Indeed, thanks for reminder. I made a new release: ocaml/opam-repository#4295

**Comment by bbatsov** [comment]
@emillon This can be closed.
