### ISSUE TITLE
Also support .utopinit

### ISSUE THREAD

**Issue by gasche** [ocaml-community/utop#144]
My current advice to people that find the default utop prompt too fancy is to add `#utop_prompt_dummy` to their `~/.ocamlinit` file. This is problematic when they run `ocaml` again, which doesn't recognize this directive; I expect people to keep using a mix of both toplevels, at least during a transition period.

I think a good solution would be to have utop load `.ocamlinit` (in the current directory or HOME) and then also load a `.utopinit` file (in the current directory or HOME) if one exists. Then utop-specific directives could go in this separate file.

(Another option would be to load _only_ utopinit, and load ocamlinit only if utopinit does not exist (which corresponds to saying that the default utopinit file is `#use ".ocamlinit";;`). This makes init files more robust and help separate the two tools, but I think it is also a more brittle behavior so I would not recommend it.)

**Comment by diml** [comment]
If we have two init files the meaning of `-init` becomes confusing. I think I prefer the last option, utop can create the utop init file if it doesn't exist (and tell the user about it).

BTW, I merged a PR recently about using the XDG conventions for init files in lambda-term: diml/lambda-term#23, so I guess utopinit would be `~/.config/utop/init.ml`.

**Comment by mars0i** [comment]
This would still be useful now, even though utop seems to have become the default repl for most people.  In addition to using utop, I'm currently also running a custom version of ocaml.  I have to use a separate .ocamlinit so that it doesn't stop reading when it sees `#utop_prompt_dummy`.

**Comment by diml** [comment]
A patch would be welcome

**Comment by mars0i** [comment]
I recently began learning OCaml.  Although from the source in uTop_main.ml, it looks like the change needed might be simple enough that I could make it, I'm encountering problems building utop at all.  It seems as if I have findlib installed, but jbuilder can't find it.  It may be that this task would require more time than I should spare--one problem leading to another, perhaps--even if it might be easy for someone more experienced.

**Comment by diml** [comment]
Ah, there is indeed an issue in the development branch. It will be fixed once the next version of findlib is released
