### ISSUE TITLE
`-stdin` processed before a `pp` has time to load

### ISSUE THREAD

**Issue by chenglou** [ocaml-community/utop#174]
Reason's rtop wraps around utop. Piping reason code into `utop -stdin -init reasonBootstrapCode.ml` doesn't work because by the time the bootstrapping code loads, utop has already processed stdin and thrown a syntax error.

What we do is to check for the `-stdin` flag in `rtop` [like so](https://github.com/facebook/reason/blob/180f26f87fa7eec5040e9107bb7f2b1662bb6870/src/rtop.sh#L31). We pre-format the code into ocaml then pass it unto utop. Works fine.

Is utop's current behavior supposed to be a bug or a feature?

cc @jordwalke

**Comment by diml** [comment]
This behavior was imported from the default toplevel, I guess the idea is that if you run in script mode you don't want to load the user init file which is probably setup for interactive use. Though if an explicit init file is specific on the command line, it seems fine to load it anyway.

Out of curiosity, why not write this script as an OCaml program? Then you could just set `Toploop.parse_toplevel_phrase` and wouldn't have to worry about this
