### ISSUE TITLE
Is ~/.utoprc supposed to be ignored?

### ISSUE THREAD

**Issue by tuncer** [ocaml-community/utop#232]
I tried to configure a monochrome color scheme so that everything is visible regardless of whatever Xdefaults may have set. However, utop seems to ignore `~/.utoprc`. Did I miss something, or is it actually not sourcing the config file? If it's ignored and supposed to be like that, maybe a colors=false would be easiest in that case?

**Comment by diml** [comment]
Are you trying to change the colors of the prompt? These are hard-coded in utop, but you can change the prompt with one of the `#utop_prompt_...` directives, or using the `UTop` module

**Comment by tuncer** [comment]
Yes, following https://github.com/diml/utop#customization, I tried to make utop source a different scheme, but this seems disabled at the moment. If you check one of the sample configs, it says [_Copy this file to ~/.utoprc_](https://github.com/diml/utop/blob/master/utoprc-light#L3).

**Comment by diml** [comment]
Yh, the file controls syntactic coloration of OCaml code but not the prompt itself. After you copy the file, things such as `let` should be colored
