### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [ocaml-community/utop#239]
```
jigao@jigao-CW35S:~$ opam install utop
[NOTE] Package utop is already installed (current version is 2.1.0).
jigao@jigao-CW35S:~$ utop

Command 'utop' not found, but can be installed with:

sudo apt install utop

jigao@jigao-CW35S:~$ 
```

Do i really installed the utop?

**Comment by aschaap** [comment]
Are you sure that the current switch is on your $PATH? Easiest way to check should be to open a new terminal (if everything went right during `opam init`). See also https://opam.ocaml.org/doc/Usage.html

**Comment by aschaap** [comment]
@songproducer Could you try `eval $(opam env)'?

**Comment by rizo** [comment]
Looks like the PATH is indeed not properly set. I recommend following this guide to properly setup the environment: https://adambard.com/blog/getting-started-with-ocaml/

**Comment by pmetzger** [comment]
Is this user error? If so, I think we should close the ticket.

**Comment by rizo** [comment]
Yeah, closing.

@cakebytheoceanLuo, let us know if you managed to install utop. Feel free to ask for help if something is not clear.
