### ISSUE TITLE
Cannot load required shared library dllcore_stubs.

### ISSUE THREAD

**Issue by ZWindL** [ocaml-community/utop#252]
OS: ArchLinux

Ocaml packages' version: 
   - ocaml 4.07.0-1
   - ocaml-compiler-libs 4.07.0-1
   - opam2 2.0.0_rc4-1 (that package is from aur)

utop version:
    - 2.2.0 (using OCaml version 4.07.0)!

$CAML_LD_LIBRARY_PATH:
    `/home/zwindl/.opam/ocaml-base-compiler/lib/stublibs:/home/zwindl/.opam/ocaml-base-compiler/lib/ocaml/stublibs:/home/zwindl/.opam/ocaml-base-compiler/lib/ocaml`

I installed `utop` with opam, and that's the `.ocamlinit` file:
```
(* Added by OPAM. *)
#use "topfind";;
#thread;;
#require "core.top";;
#require "core.syntax";;

let () =
  try Topdirs.dir_directory (Sys.getenv "OCAML_TOPLEVEL_PATH")
  with Not_found -> ()
;;
```

It runs normally but print this error message:
```
Cannot load required shared library dllcore_stubs.
Reason: /home/zwindl/.opam/ocaml-base-compiler/lib/stublibs/dllcore_stubs.so: /home/zwindl/.opam/ocaml-base-compiler/lib/stublibs/dllcore_stubs.so: undefined symbol: makedev.
```

And when I try to build some samples with `corebuild`, it prints:
```
+ ocamlfind ocamlopt -linkpkg -g -thread -package core test.cmx -o test.native
/usr/bin/ld: /home/zwindl/.opam/ocaml-base-compiler/lib/core/libcore_stubs.a(unix_stubs.o): in function `unix_mknod_stub':
/home/zwindl/.opam/ocaml-base-compiler/.opam-switch/build/core.v0.11.2/_build/default/src/unix_stubs.c:281: undefined reference to `makedev'
collect2: 错误：ld 返回 1
File "caml_startup", line 1:
Error: Error during linking
Command exited with code 2.
Compilation unsuccessful after building 4 targets (3 cached) in 00:00:00.
```

I'm not sure these two issues have connection.

**Comment by diml** [comment]
The two are the same error. The C compiler accepted to compile a file with a reference to a `makedev` function, but at link time nothing is providing it. It's a problem with the core library, please open a ticket on https://github.com/janestreet/core

**Comment by ZWindL** [comment]
OK, thanks.

**Comment by diml** [comment]
Adding a link to the core issue for future references: https://github.com/janestreet/core/issues/117
