### ISSUE TITLE
utop emacs completion-at-point-functions support?

### ISSUE THREAD

**Issue by ghost** [ocaml-community/utop#261]
Hi. 
Is it possible to add ``completion-at-point-functions`` for utop.el?
I don't want a completion list displayed everytime when I try to complete something, when I don't have company-mode enabled. 
You can use any backend when you have a ``completion-at-point-functions`` (e.g. ivy and company).
I think a ``completion-at-point-functions`` support will be convinent.
Thanks.

**Comment by rgrinberg** [comment]
Sure, feel free to add them but AFAIK the main issue is that you can't support `completion-at-point` asynchronously.
