### ISSUE TITLE
Documentation for utop

### ISSUE THREAD

**Issue by amirmc** [ocaml-community/utop#27]
A reminder, as per email thread :)

> There is no such documentation for utop at the moment.  Most parts of
> chapter 9 from the OCaml manual still apply to utop so it should be
> easy to copy&paste and adapt it to utop.

https://sympa.inria.fr/sympa/arc/caml-list/2013-07/msg00050.html

**Comment by bbatsov** [comment]
@emillon Probably no longer relevant?
