### ISSUE TITLE
BUG!! Cannot load required shared library: dllcore_stubs library

### ISSUE THREAD

**Issue by gabefighter99** [ocaml-community/utop#275]
MacBook Air
macOS High Sierra v10.13.6

`$ uname -a`

Output:
`Darwin YNC28012019P11.local 17.7.0 Darwin Kernel Version 17.7.0: Thu Dec 20 21:47:19 PST 2018; root:xnu-4570.71.22~1/RELEASE_X86_64 x86_64`

Reproducible steps:

clone the following repository (ignore everything, it's for a class, not important):

`$ git clone https://github.com/ilyasergey/ysc2229-part-two.git`
(may be necessary to clone part one also):
`$ git clone https://github.com/ilyasergey/ysc2229-part-one.git`

`$ git branch`
`$ git checkout week10`
`$ make clean`
`$ make`
`$ opam install .`
`$ utop`

Until here everything should run fine. "make" will give you a good 50000 warnings, but nothing should be serious.

Here's where things go wrong:

`#utop: #require "ysc2229-part-two";;`

Output:
`Cannot load required shared library dllcore_stubs.
Reason: /Users/cipe/.opam/default/lib/stublibs/dllcore_stubs.so: dlopen(/Users/cipe/.opam/default/lib/stublibs/dllcore_stubs.so, 10): Symbol not found: _caml_exn_Invalid_argument
  Referenced from: /Users/cipe/.opam/default/lib/stublibs/dllcore_stubs.so
  Expected in: flat namespace
 in /Users/cipe/.opam/default/lib/stublibs/dllcore_stubs.so.
Error: Reference to undefined global 'Core__Core_sys' `

Furthermore:

Exit utop.

Retry with:
`$ make clean`
`$ make`
`$ dune utop . --profile release`

Using this method we fail to enter utop even with the following output:

`ocamlc .utop/utop.exe (exit 2)
(cd _build/default && /usr/local/bin/ocamlc.opt -w -40 -w -24 -g -o
...
)
Undefined symbols for architecture x86_64:
  "_caml_exn_Invalid_argument", referenced from:
      _string_ocaml_to_c in libcore_stubs.a(ocaml_utils_stubs.o)
      _core_unix_remove in libcore_stubs.a(unix_stubs.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
File "_none_", line 1:
Error: Error while building custom runtime system`

Comments:
A fellow student got the exact same error. Also on a Macbook Air but Im not sure about his kernel.

**Comment by diml** [comment]
This is an issue with Core library, the next minor release will fix the issue.

https://github.com/janestreet/core/issues/125

**Comment by sergi** [comment]
Hi,

I still have this error and I am using the latest version of core (v0.12.2)

```
Cannot load required shared library dllcore_stubs.
Reason: /Users/sergimansilla/.opam/default/lib/stublibs/dllcore_stubs.so: dlopen(/Users/sergimansilla/.opam/default/lib/stublibs/dllcore_stubs.so, 10): Symbol not found: _caml_exn_Invalid_argument
  Referenced from: /Users/sergimansilla/.opam/default/lib/stublibs/dllcore_stubs.so
  Expected in: flat namespace
 in /Users/sergimansilla/.opam/default/lib/stublibs/dllcore_stubs.so.
Exception: Symtable.Error _.
Raised at file "bytecomp/symtable.ml", line 75, characters 9-49
Called from file "bytecomp/symtable.ml", line 330, characters 24-45
Called from file "toplevel/toploop.ml", line 66, characters 16-32
Called from file "toplevel/toploop.ml", line 66, characters 16-32
Called from file "toplevel/topdirs.ml", line 361, characters 12-46
Called from file "toplevel/toploop.ml", line 361, characters 69-74
Called from file "toplevel/toploop.ml", line 370, characters 6-42
Re-raised at file "toplevel/toploop.ml", line 373, characters 10-13
Called from file "top/core_install_printers.ml", line 15, characters 4-19
Called from file "top/core_install_printers.ml", line 18, characters 9-36
Called from file "toplevel/topdirs.ml", line 157, characters 11-23
```

**Comment by diml** [comment]
That's a core issue, could you open a ticket on github.com/janestreet/core?

**Comment by sergi** [comment]
Of course, thanks.
