### ISSUE TITLE
Invalid_argument("String.sub / Bytes.sub") on startup

### ISSUE THREAD

**Issue by correct-chris** [ocaml-community/utop#287]
I have this bug whenever I try to use utop 2.4. 2.3 works fine.
```
Fatal error: exception Invalid_argument("String.sub / Bytes.sub")
```
OS: 64-bit Arch Linux
This happens on ocaml 4.07.1 and 4.08.0, even on a fresh opam switch with no `.ocamlinit` or `.utoprc`.

**Comment by pmetzger** [comment]
It doesn't happen for me (MacOS), so clearly something is rather different about your setup. Did you build your compiler and utop from opam?

**Comment by kandu** [comment]
If the issue disappears after you backup and delete the `~/.utop-history` file then would you please paste the output of `locale` and attach(not paste) your backup file in the comment.

**Comment by correct-chris** [comment]
> delete the ~/.utop-history file

That fixed it.

Output of `locale`:
```
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```
[utop-history.txt](https://github.com/ocaml-community/utop/files/3310510/utop-history.txt)

**Comment by kandu** [comment]
The '😀' character, which is of length 4 bytes, triggered the bug.

I should also update the width table of CharInfo_width for it.

**Comment by kandu** [comment]
Hi, @pmetzger. Should we make a new minor release for zed?

**Comment by pmetzger** [comment]
@kandu Given a bug this irritating? I'd say a new minor/patch release would be good, yes.
