### ISSUE TITLE
Remove support for camlp4 and corresponding directives

### ISSUE THREAD

**Issue by XVilka** [ocaml-community/utop#289]
Camlp4 is certainly dead, maybe it is finally time to kill it here as well?

https://github.com/ocaml-community/utop/issues/163

**Comment by pmetzger** [comment]
Why don't you submit a patch?

**Comment by XVilka** [comment]
I will, just checking first if it will be accepted, to reduce amount of unnecessary work.

**Comment by XVilka** [comment]
In fact it limits the support for building for OCaml 4.08, since camlp4 is not yet ported to that version: https://github.com/ocaml/camlp4/issues/151

**Comment by XVilka** [comment]
I sent a pull request: 
https://github.com/ocaml-community/utop/pull/290

Please take a look.

**Comment by XVilka** [comment]
Finally closed in https://github.com/ocaml-community/utop/commit/9da0951274af3fcadfd7b40fc582ab00539c5884
