### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by XVilka** [ocaml-community/utop#295]
Important for the updating on Debian - see https://github.com/ocaml/camlp4/issues/151#issuecomment-518998527 and below.

**Comment by pmetzger** [comment]
I don't understand what this PR is asking us to do?

**Comment by XVilka** [comment]
What PR?

**Comment by pmetzger** [comment]
I meant issue. What is it that you want done? Please explain it. I have no idea what this issue is asking us to do.

**Comment by XVilka** [comment]
@pmetzger new release for the opam. So the Debian can update. Since last camlp4 remnants were removed from the code, and Debian works on deprecating camlp4 as well.

**Comment by pmetzger** [comment]
So all you're asking is that there be a new release? @kandu, do you want to cut one?

**Comment by XVilka** [comment]
@pmetzger exactly.

**Comment by pmetzger** [comment]
@XVilka Next time, add some explanatory text, as in "It seems like a good time to cut release 99.3; several important updates were made and this will enable the new holographic display terminal features on Windows 13."

**Comment by kandu** [comment]
@XVilka thought that you were Sherlock Holmes. Sadly you just disappointed him (\~\_\~;)

**Comment by kandu** [comment]
ok, major or minor?

**Comment by XVilka** [comment]
@kandu I think minor is more than enough, there are only 6 commits after the last release:
https://github.com/ocaml-community/utop/compare/2.4.0...master
