### ISSUE TITLE
doesnt compile on 4.09.0+beta2

### ISSUE THREAD

**Issue by avsm** [ocaml-community/utop#298]
There are some breaking changes in 4.09 that break compilation of utop:

- Env.Persistent_signature needs to be renamed to Persistent_env.Persistent_signature (just a search-and-replace fixes this
- Obj.truncate is now deprecated, and there is some gnarly looking code in the main loop that blits over Sys.argv using it:
```
  let len = Array.length Sys.argv - !Arg.current in
  Array.blit Sys.argv !Arg.current Sys.argv 0 len;
  Obj.truncate (Obj.repr Sys.argv) len;
```
- [ ] TypedtreeIter.DefaultIteratorArgument needs to be ported to use Tast_iterator instead. I've not looked into what this involves yet -- help welcome

**Comment by pmetzger** [comment]
Thanks for looking at this? Do you think you could submit a PR for the portion you've done (`Env.Persistent_signature`) just so that we can get those out of the way? We can then address the `Obj.truncate` and `TypedtreeIter` portions. BTW, when is 4.09 due out?

**Comment by pmetzger** [comment]
(Oh, and I believe you have commit access, if not, let me know so that can be fixed.)

**Comment by Octachron** [comment]
I will have a look at the issues this afternoon. 4.09 is due very soon.
