### ISSUE TITLE
#typeof misparses values containing dots

### ISSUE THREAD

**Issue by Octachron** [ocaml-community/utop#301]
Trying to get the type of `+.` currently fails with

```OCaml
#typeof "+.";;
Unknown type
```
This is due to the use of `Longident.parse` which only works on a subset of `Longident`s. In the case of `+.`, it misparses the value as `Ldot(Lident "+", "")` and then fails to find such value.

**Comment by pmetzger** [comment]
@Octachron do you have a workaround? (Feel free to patch this if you have a clean one...)

**Comment by Octachron** [comment]
My current plan is to expose a better parser function in compilerlibs, and then use it in utop (so in 4.10 or 4.11). A handwritten parser sounds like too much maintenance work.

**Comment by pmetzger** [comment]
That seems reasonable. In which case, we can leave this open until 4.10 makes it available. Is that your preferred outcome for the moment as well?

**Comment by Octachron** [comment]
Indeed. I essentially opened this issue because I expected the right fix to take some time to propagate.

**Comment by kandu** [comment]
Parse.longident recognizes `(+)` and `(+.)`, but it complains "syntax error" if the brackets are stripped.
Am I doing something wrong?

**Comment by kandu** [comment]
``` ocaml
utop # Parse.longident (Lexing.from_string "+.");;
Exception:
Syntaxerr.Error
 (Syntaxerr.Other
   {Location.loc_start =
     {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 0};
    loc_end = {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 2};
    loc_ghost = false}).
Raised at Parse.wrap in file "parsing/parse.ml", line 65, characters 6-49
Called from Toploop.load_lambda in file "toplevel/toploop.ml", line 212, characters 17-27
```

**Comment by kandu** [comment]
``` ocaml
utop # Parse.longident (Lexing.from_string "+");;
Exception:
Syntaxerr.Error
 (Syntaxerr.Other
   {Location.loc_start =
     {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 0};
    loc_end = {Lexing.pos_fname = ""; pos_lnum = 1; pos_bol = 0; pos_cnum = 1};
    loc_ghost = false}).
Raised at Parse.wrap in file "parsing/parse.ml", line 65, characters 6-49
Called from Toploop.load_lambda in file "toplevel/toploop.ml", line 212, characters 17-27
```

**Comment by kandu** [comment]
And `Longident.unflatten` doesn't work in this case either.

**Comment by Octachron** [comment]
The parse functions are indeed stricter than `Longident.parse`: they only accept input that can are valid identifiers, so indeed `+` is rejected and `(+)` is accepted. How problematic do you think it is to reject "+"?

**Comment by kandu** [comment]
Ah, that makes sense. Just because Longident.parse recognizes `+`, so the behavior is slightly different.
