### ISSUE TITLE
Add documentation for running `dune utop` within Emacs

### ISSUE THREAD

**Issue by samarthkishor** [ocaml-community/utop#306]
It would be helpful to have a note in the "Integration with emacs" section of the readme that explains how to run `dune utop` within Emacs.

This should do the trick: `(setq utop-command "opam config exec -- dune utop . -- -emacs")`

I got the relevant elisp from here: https://discuss.ocaml.org/t/jbuilder-utop-from-emacs-facility/2176/7

**Comment by pmetzger** [comment]
If you would like to do a pull request with some reasonable language in it, we can integrate it.

**Comment by ejmg** [comment]
#307 should have closed this issue *but* I do want to report that the solution does not work for me with the following system info:
- emacs v29.0.50
- opam v2.1.1
- dune v2.9.1
- utop v2.8.0
- utop.el v1.11 (package-version: 20210607.1941)

the default command, `utop -emacs` as well as that recommended in the README, `opam config exec -- utop -emacs` both work just fine besides directives like `open MyModuleFoo;;` in a project local .ocamlinit file no longer working.

The current suggested solution for loading utop via dune within emacs is a hard failure and only gives an opaque `Process utop exited with code 1` error.
