### ISSUE TITLE
pasting input in vi mode

### ISSUE THREAD

**Issue by nilsbecker** [ocaml-community/utop#319]
in the new vi-edit mode, utop hangs when i paste input that spans multiple toplevel phrases.

e.g. 
```
t;;

t;;
```
will let utop hang when in vi mode (not in emacs line editing mode).

context: i am using utop within tmux together with vim-slime to receive input from vim. however, the hang also happens with standard paste from the system clipboard. macos.

in general, it might be good to have a universal escape sequence to get out of any situation where input is frozen. something like `esc-esc-esc` on vim i believe

**Comment by kandu** [comment]
> in general, it might be good to have a universal escape sequence to get out of any situation where input is frozen. something like esc-esc-esc on vim i believe

@nilsbecker Thanks for reporting this irritating bug. Since `LTerm_read_line` is now a multi-thread(or multi-promise) system, some priority or synchronization issues, 2 or 3 at most are waiting to be caught. In this case, an escape keyseq will complicates the system and increase the number of lurkers manyfold. Since you've already caught one, there will be at most 1 or 2 bugs lurking. To be a hunter is better than to be a guard for now ;)

Bugfix version will be released within 6 hours.

**Comment by kandu** [comment]
Hi, @nilsbecker, lambda-term 3.0.1 was published.

The issues was closed automatically by the linked PR, but I'm not familiar with tmux or vim-slime, so maybe you could make a confirmation that it works in your context?

**Comment by nilsbecker** [comment]
i tried it with lambda-term 3.0.1. this fixes the hang, so tmux with vim-slime is usable now.  however, it seems that pasted text is now handled slower; i can follow the pasted text appear in the terminal characer-by-character, which was not possible before. it's not disturbingly slow but noticeable. this slow-down happens in vi edit mode and in emacs edit mode

**Comment by kandu** [comment]
Yeah, after some essential features are implemented in release 3.1.0. We'll slow down the development and take some time to polish it. for example, the functor in charInfo-width requires the unicode-string module to implement only random access, that's too minimum. We'll demand sequence access later to improve the performance.
besides the design flaw, there are points waiting to be optimized scattered among these projects.
Would you like to be a hunter for a while and catch some of them?   (^_-)
