### ISSUE TITLE
Add OCaml 4.11 to CI matrix

### ISSUE THREAD

**Issue by kandu** [ocaml-community/utop#321]
OCaml 4.10 was now in its stable phase, so maybe we could change the switch from beta to stable version?

And OCaml 4.11 beta was just released, shall we add this beta version to the CI matrix?

**Comment by kandu** [comment]
Hi, @kit-ty-kate ! Do you want to make a PR?

**Comment by kit-ty-kate** [comment]
I do, I'll make a PR in a bit
