### ISSUE TITLE
pasting input into utop

### ISSUE THREAD

**Issue by nilsbecker** [ocaml-community/utop#324]
Text pasted from the system clipboard is interpreted character-by-character. This generates a lot of unnecessary overhead. For instance, all completion options are shown at each character. As a result, pasting code is slow. 

I believe this is a regression introduced in UTop 2.5.0 in order to work around a problem in the new vi edit mode.

**Comment by kandu** [comment]
Hi, @nilsbecker 
Sorry for the late response.
Would you please record the window so the issue will be exposed more intuitive.

run `xwininfo`, click the terminal window to get the x, y, width, height info of the window and then `byzanz-record -x x -y x -w width -h height -d time record-name.gif` or any recorder you prefer.

You may record the pasting processing for utop version 2.3.0, 2.4.0 and 2.5.0 so The issue will be located precisely.

**Comment by mvanier** [comment]
I'm running utop on Mac OS X and I've noticed this too.  I also noticed that the C-y ("yank") keybinding doesn't seem to do anything (even when there is something in the clipboard and Command-y works), though this may be a separate issue.

**Comment by mvanier** [comment]
![output](https://user-images.githubusercontent.com/1724336/82614568-04162980-9b7d-11ea-953a-5a86c25dd57f.gif)

**Comment by nilsbecker** [comment]
thanks @mvanier  for recording, this is what i see as well.

**Comment by nilsbecker** [comment]
this is a recording with utop 2.4.3. the code example is probably not the best but i hope this shows that pasting is essentially instantaneous.

![animation](https://user-images.githubusercontent.com/177614/82653640-cfa77980-9c1f-11ea-904d-d04536d6af1b.gif)

**Comment by kandu** [comment]
Thanks for reporting this, @nilsbecker and @mvanier.

> I'm running utop on Mac OS X and I've noticed this too. I also noticed that the C-y ("yank") keybinding doesn't seem to do anything (even when there is something in the clipboard and Command-y works), though this may be a separate issue.
> 
> EDIT: C-y does in fact work in some circumstances. If you do a C-u to kill a line, then C-y recalls it. C-y just doesn't seem to interact with the system clipboard (on both Mac OS X and Linux).

This is because utop, lambda-term are not x-window or gui system aware. The clipboard, and the upcoming register support are builtin private storage.

**Comment by mvanier** [comment]
Thanks for the clarification.  Since the list of key bindings includes this:

C-y         : yank                          -> paste the contents of the clipboard at current position.

I would argument that the wording is very confusing.  Most people will read "clipboard" as "system clipboard" not as "private clipboard for utop that is not related to the system clipboard".  This should be a separate issue, though.
