### ISSUE TITLE
installing utop

### ISSUE THREAD

**Issue by OrionRandD** [ocaml-community/utop#342]
The easiest and recommended way of installing utop is via opam:
$ opam install utop

Now I can install utop in debian as well with:
sudo apt install utop

:)

**Comment by pmetzger** [comment]
I'm not sure what the issue here is?

**Comment by bbatsov** [comment]
I think this can be closed.

**Comment by jjoneslivingstone** [comment]
Hi, I would like to install UTop for OCaml on Visual code 'cause in need of a line editor. Any clue about the how?

Thank you.

**Comment by bbatsov** [comment]
@jjoneslivingstone You have to install Opam first. See https://opam.ocaml.org/doc/Install.html

**Comment by OrionRandD** [comment]
I do not use Macs, but in linux, debian and derivatives, it is as simple as this:
sudo apt install utop
In Macs, you can install it from sources.
Just clone the repo, cd into it and issue the commands:
make
make install 
make doc

As it is written here:
https://github.com/ocaml-community/utop

**Comment by jjoneslivingstone** [comment]
Hi,

@OrionRandD  : cloned the repository, cded into it, typed 'make' and got this:

jjoneslivingstone@jjonesltonesMBP utop-master % make
dune build
make: dune: No such file or directory
make: *** [all] Error 1

@bbatsov: I now got installed opam and utop via zsh. Upgraded the shell environment via 

 eval $(opam env)

as requested. On OCaml in Visual Code nothing happened. No colours discerning commands and such, and no line editor. Any other step I could take?

Thank you.

**Comment by OrionRandD** [comment]
> dune build
> make: dune: No such file or directory

https://medium.com/@argent_smith/beginners-ocaml-setup-on-mac-fc206747b1ab
http://ocamlverse.net/content/quickstart_ocaml_project_dune.html

I do not use MacOS and VScode,
but, the above links, perhaps, can help you...

**Comment by jjoneslivingstone** [comment]
@OrionRandD : did this:

jjoneslivingstone@jjonesltonesMBP utop-master % dune init project Dune_1
Success: initialized project component named Dune_1
jjoneslivingstone@jjonesltonesMBP utop-master % dune build
jjoneslivingstone@jjonesltonesMBP utop-master % make 
dune build
jjoneslivingstone@jjonesltonesMBP utop-master % make install
dune install 

I now have utop running on terminal. Plus copied utoprc-dark to ~/.utoprc but nothing changes in a refreshed OCaml Visual Code shell.

**Comment by jjoneslivingstone** [comment]
@OrionRandD 

I think it might be about locking its dependencies for use in "other installation" (http://ocamlverse.net/content/quickstart_ocaml_project_dune.html). At the momento I got this running opam lock in dune folder project:

jjoneslivingstone@jjoneslivingstones-MacBook-Pro Dune_1 % opam lock .
[ERROR] Skipping Dune_1.~dev, dependencies are not satisfied in this switch,
        not installed packages are:
          - dune (>= 3.4)

No lock file generated

and then this trying to install the requested dune package using "dune install" in dune project folder:

zsh: parse error near `)'

I do not know the exact syntax here.

While if I run depends I get this: 

jjoneslivingstone@jjoneslivingstones-MacBook-Pro Dune_1 % (depends caml>= 4.14.0)
zsh: command not found: depends

Thank you.

**Comment by OrionRandD** [comment]
> @OrionRandD
> 
> I think it might be about locking its dependencies for use in "other installation" (http://ocamlverse.net/content/quickstart_ocaml_project_dune.html). At the momento I got this running opam lock in dune folder project:
> 
> jjoneslivingstone@jjoneslivingstones-MacBook-Pro Dune_1 % opam lock . [ERROR] Skipping Dune_1.~dev, dependencies are not satisfied in this switch, not installed packages are: - dune (>= 3.4)
> 
> No lock file generated
> 
> and then this trying to install the requested dune package using "dune install" in dune project folder:
> 
> zsh: parse error near `)'
> 
> I do not know the exact syntax here.
> 
> While if I run depends I get this:
> 
> jjoneslivingstone@jjoneslivingstones-MacBook-Pro Dune_1 % (depends caml>= 4.14.0) zsh: command not found: depends
> 
> Thank you.

I think your zsh is also misconfigured...
But, here, I cannot help. I do not use zsh... but simple bash.
Perhaps, consider installing a VM like virtualbox, then install a debian distro in it and then, opam/utop.
You can do this in less than 15min.

**Comment by jjoneslivingstone** [comment]
About installing a Virtual Machine, I think it might be nonsense. 

I recently switched from zsh to bash to perform a re-installation of opam / utop. Then back to zsh because how wasn't running anymore on Visual Code. 

I thought there might be maybe a way to install utop directly into the Visual Code environment. I ought to try this yet but I do not know if is possible considering the request for extra dune dependencies (which I will try to get seeing in time). 

or

reinstall opam and utop via brew commands?

Any other help or idea is welcome. 

Thank you.

**Comment by OrionRandD** [comment]
> About installing a Virtual Machine, I think it might be nonsense.
> 
> I recently switched from zsh to bash to perform a re-installation of opam / utop. Then back to zsh because how wasn't running anymore on Visual Code.
> 
> I thought there might be maybe a way to install utop directly into the Visual Code environment. I ought to try this yet but I do not know if is possible considering the request for extra dune dependencies (which I will try to get seeing in time).
> 
> or
> 
> reinstall opam and utop via brew commands?
> 
> Any other help or idea is welcome.
> 
> Thank you.

Yes. You are right. I only gave the VM suggestion because I thought you were in a hurry to perform some kind of urgent work. But, definitely, there must be a solution for your case...

**Comment by jjoneslivingstone** [comment]
In 15min.

**Comment by pmetzger** [comment]
You do not want to hand install from sources. You want to install opam and have it build this stuff for you.

**Comment by jjoneslivingstone** [comment]
I managed to install again utop directly in vscode environment via its terminal bash with:

opam install utop

had a slowed reboot with a shell not loading properly and HTML code appearing on the right hand of the vscode GUI. Closed the thing and reopened it couple of times and then it flowed pretty ok like before. 

This seems the right way to me...made utop run in effect on vscode, but still got no differences in HOL though did the 

eval `opam config env`

Also ran 'rlwrap ocaml' too, but HOL still got no line editing feature.

**Comment by pmetzger** [comment]
@jjoneslivingstone This is not a place to get support for opam, utop, etc. It's a bug reporting service. Try asking for help on something like the OCaml discuss website.

**Comment by pmetzger** [comment]
@jjoneslivingstone There's no bug here, and this is the github bug reporting system.
