### ISSUE TITLE
How to setup utop completion?

### ISSUE THREAD

**Issue by sheepduke** [ocaml-community/utop#344]
Folks, I was trying to use utop in the Emacs. I set it up using the following configuration and it almost worked.

However, the `utop-complete` did not work. No completion was provided in the utop buffer. Please note that that auto completion worked in the tuareg buffer. 

Where could be the problem? Could you please give me some clues?

```emacs-lisp
;;; Major mode for editing OCaml files.
(use-package tuareg :ensure)

;;; Auto completion and more.
(use-package merlin :ensure
  :after tuareg
  
  :hook
  (tuareg-mode . merlin-mode))

;; Consistent indentation.
(use-package ocp-indent :ensure
  :after tuareg
  
  :hook
  (tuareg-mode . ocp-setup-indent))

;;; Type tips.
(use-package merlin-eldoc :ensure
  :after merlin
  
  :hook
  (tuareg-mode . merlin-eldoc-setup))

;;; Build system.
(use-package dune :ensure)

(use-package utop :ensure
  :after tuareg

  :hook
  (tuareg-mode . utop-minor-mode))
```

**Comment by E-Neo** [comment]
Maybe completion-mode is not enabled in utop-mode?
Try append ```(utop-mode . company-mode)``` to the utop hook
