### ISSUE TITLE
utop doesn't correctly colorize errors in emacs.

### ISSUE THREAD

**Issue by chripell** [ocaml-community/utop#349]
At some point the output from ocaml compiler changed and it adds also line information. utop doesn't correctly parse the line part. This is a simple session which shows the problem (I use it also to test the error spanning multiple lines):

```
utop[0]> let f x = x + 1;;
val f : int -> int = <fun>
utop[1]> f 1;;
- : int = 2
utop[2]> f "a";;
Line 1, characters 2-5:
Error: This expression has type string but an expression was expected of type
         int
utop[3]> f "a
b";;
Lines 1-2, characters 2-2:
Error: This expression has type string but an expression was expected of type
         int
```

I expect to have the string colored in red, instead I just get the position of the error. This makes really difficult to understand where the error is for long expressions.

I will propose a PR shortly.

Thanks!

**Comment by pmetzger** [comment]
Thanks for re-opening this! And I'm sorry that reviews were slow for a while; we're trying to be better about that now.
