### ISSUE TITLE
utop in Emacs couldn't auto-complete after dot

### ISSUE THREAD

**Issue by E-Neo** [ocaml-community/utop#358]
Emacs fails to auto-complete inputs such as "List.m TAB".
IMHO, the string-prefix-p test is the reason, because the prefix "List." is not shown in the completion data.
```
$ utop -emacs
protocol-version:1
phrase-terminator:;;
stdout:Welcome to utop version 2.7.0 (using OCaml version 4.12.0)!
stdout:
prompt:
complete-company:
data:Li
end:
completion-start:
completion:List
completion:ListLabels
completion-stop:
complete-company:
data:List.m
end:
completion-start:
completion:map
completion:map2
completion:mapi
completion:mem
completion:mem_assoc
completion:mem_assq
completion:memq
completion:merge
completion-stop:
```
https://github.com/ocaml-community/utop/blob/bac3946079a98df00f31656dc10c6c9f1a8bc422/src/top/utop.el#L650-L655

**Comment by idurand** [comment]
I have the same problem since my laptop was stolen and I installed a new one.
I am suppose to give a class about ocaml lists soon and my slides say that
in order to see all List function one need only to do
List <TAB>
but it does not work anymore.
Did you ever find a solution to this problem?

**Comment by bbatsov** [comment]
See my proposed fix here https://github.com/ocaml-community/utop/pull/388
