### ISSUE TITLE
Move histfile to $XDG_CACHE_HOME on linux

### ISSUE THREAD

**Issue by exorcist365** [ocaml-community/utop#361]

**Comment by zapashcanon** [comment]
In [directories](https://github.com/OCamlPro/directories) you can also get the macOS and Windows equivalent.

**Comment by pmetzger** [comment]
@exorcist365 You are more likely to get this fixed if you propose a pull request with the change you want...

**Comment by exorcist365** [comment]
> @exorcist365 You are more likely to get this fixed if you propose a pull request with the change you want...

Alright, I have opened #362, hopefully it gets merged.
