### ISSUE TITLE
manual page is misleading about options

### ISSUE THREAD

**Issue by lindig** [ocaml-community/utop#363]
The man page says about options:

```
OPTIONS
       Same as ocaml(1).
```

That is not correct as utop supports more options. It would be better to direct the user to `utop --help`.

**Comment by pmetzger** [comment]
@lindig would you like to do a merge request with a fix?

**Comment by lindig** [comment]
Will do

**Comment by lindig** [comment]
That was merged - but see also https://github.com/ocaml-community/utop/pull/365

**Comment by lindig** [comment]
In any case, I believe this issue can be closed as the manual now points to the `-help` option.

**Comment by pmetzger** [comment]
Cool. I'll close it. Thanks for working on this!
