### ISSUE TITLE
Label all Emacs-related issues

### ISSUE THREAD

**Issue by bbatsov** [ocaml-community/utop#380]
I think it's a good idea to label different type of issues, so they are easier to discover. I'd appreciate adding an "Emacs" label as it seems 1/4 of all open tickets are related to `utop.el`.

**Comment by pmetzger** [comment]
Which issues do you want labeled? Give us a list.

**Comment by bbatsov** [comment]
@pmetzger I see 26 open issues that mention Emacs currently https://github.com/ocaml-community/utop/issues?q=is%3Aissue+is%3Aopen+emacs

**Comment by emillon** [comment]
done. I don't think we have a lot of people able to fix these, so if you're comfortable with emacs there's probably a lot to improve here :)
