### ISSUE TITLE
Target a newer Emacs version in utop.el

### ISSUE THREAD

**Issue by bbatsov** [ocaml-community/utop#389]
Currently utop.el targets the ancient Emacs 24.1 that was released way back in 2012 and pretty much noone uses these days. Even the most conservative Emacs distros like Debian and RHEL have Emacs 27 these days, so I'd propose bumping the required Emacs to 26.1. (I like the idea of supporting the last 3 major Emacs releases in general) Adopting a newer Emacs will allows to modernize and clean up the codebase down the road. 

There are also indications that utop.el doesn't actually work on Emacs 24 anyways (see https://github.com/ocaml-community/utop/issues/258#issuecomment-424155480). 

Any objections?

**Comment by rgrinberg** [comment]
No objections.

**Comment by bbatsov** [comment]
Here's the PR https://github.com/ocaml-community/utop/pull/390
