### ISSUE TITLE
Xdg module unbound with utop 2.13.0

### ISSUE THREAD

**Issue by SnarkBoojum** [ocaml-community/utop#446]
With utop 2.13.0:
```
utop # #use_output "dune utop";;
File "_none_", line 1:             
Error: Module `Xdg' is unavailable (required by `UTop_private')
Command exited with code 1.        
```
and indeed, if I try "open Xdg;;" in "utop", it fails -- I have to run "utop -I /usr/lib/ocaml/xdg" to make "open Xdg;;" work. But that doesn't fix the #use_output line...

**Comment by emillon** [comment]
Hi.
Thanks for the report. How did you install `utop`?

> `#use_output "dune utop";;`

This is not something that's supposed to work: `dune utop` (from your shell) is supposed to start `utop` with the right modules loaded. Does that work?

(for `#use_output`, the command to call is `#use_output "dune top"` but it's a different thing)

**Comment by SnarkBoojum** [comment]
No, "dune utop" doesn't work -- since the project doesn't build completely and that's actually what I want to debug!

**Comment by emillon** [comment]
what happens when you run `dune utop` from the shell?

**Comment by emillon** [comment]
hmm, forget about this. does your debugging approach work with an older version of utop? (also, how did you install utop)

**Comment by SnarkBoojum** [comment]
I install utop with the Debian package -- I'm part of the team preparing it. It did work in previous versions. I can use this debugging trick with the regular ocaml toplevel, but as you know it's a bit uncomfortable to work with.

**Comment by SnarkBoojum** [comment]
When I run "dune utop", it just sits telling me the compilation isn't done... one file is missing - the one failing!

**Comment by emillon** [comment]
> It did work in previous versions.

[utop 2.13.0 added a dependency against xdg >= 3.9.0](https://github.com/ocaml-community/utop/pull/431), have you added that dependency on the Debian side? If so, do you have a log of utop 2.13.0 being built with it?

**Comment by SnarkBoojum** [comment]
Well, xdg isn't a separate package -- it's shipped with the dune package. The relevant part of the log is:
```
make[1]: Entering directory '/home/jpuydt/Debian/build/utop-2.13.0'
dune build -p utop
make[1]: Leaving directory '/home/jpuydt/Debian/build/utop-2.13.0'
```
where I can only see that I should find a way to make the build more verbose on what it does!

But there are neither error nor warning: dune does find xdg required from src/lib/dune.

**Comment by emillon** [comment]
I think we need to take one step back: what steps, exactly, used to work with utop 2.12.1, and do not work with the version you're packaging? If it's the `dune utop` command, in which project are you running this command?
