### ISSUE TITLE
OCaml 5.2 support

### ISSUE THREAD

**Issue by emillon** [ocaml-community/utop#466]
At the moment, `utop` is not compatible with OCaml 5.2.0 (or rather, with the current version of `trunk`, since 5.2.0 has not been released  yet).

To support this, it is necessary to update `uTop_compat.ml` to account for the API changes in the compiler libs.
This is usually straightforward (one parameter is added, a type becomes abstract, etc) but requires good familiarity with OCaml and build tools (`dune`, `opam` and `cppo`).

I can provide help with this.

**Comment by huwaireb** [comment]
🧇 I can take care of this, i've already gotten something building on the OCaml 5.2 trunk switch, just have some questions regarding retaining compatibility with the previous implementations, in this case load_path < 5.2 has a different implementation and interface than load_path >= 5.2. I can proceed to open a PR if that's fine and we can discuss my questions there.
