### ISSUE TITLE
type aliases weird behavior

### ISSUE THREAD

**Issue by puitgfr** [ocaml-community/utop#476]
Type aliases seem to be incorrectly managed.
```ShellSession
§ utop
Welcome to utop version 2.13.1 (using OCaml version 4.14.1)!
Type #utop_help for help about using utop.

utop [0]:  type nat = int  (* ≥ 0 *) ;;
type nat = int
utop [1]:  let rec fact (n:nat) : nat =
             if n <= 1 then 1 else n * fact (n-1) ;;
utop [2]:  fact 5 ;;
- : nat = 120
```
So far, so good. But :
```ShellSession
utop [3]: (+) ;;
- : nat -> nat -> nat = <fun>
```
Maybe I'm missing something about type aliases, but I 'd like the type of `(+)` to remain ` int -> int -> int`, as it is the case in standard toplevel `ocaml`.

**Comment by emillon** [comment]
That's because `utop` uses `-short-paths` by default. You will get the same behavior in a `ocaml` toplevel if you pass `-short-paths`. You can disable this behavior in `utop` by passing `-no-short-paths`.
Thanks

**Comment by puitgfr** [comment]
Thanks for your quick reply. Indeed, it works with `-no-short-paths`. I wasn't aware of this option :+1:
