### ISSUE TITLE
Unable to get `#edit_mode_vi` to work

### ISSUE THREAD

**Issue by SinTan1729** [ocaml-community/utop#482]
I have the following `~/.config/utop/init.ml`.
```
#utop_prompt_fancy_dark;;
#edit_mode_vi;;
```
The prompt change works, but `#edit_mode_vi` doesn't. Typing it directly in `utop` also does nothing. Am I missing something here?

**Comment by pmetzger** [comment]
I think this is working, so at best there might be a reason to document the behavior.

**Comment by SinTan1729** [comment]
That was the case. It works after hitting <kbd>Esc</kbd>.
