### ISSUE TITLE
Fatal error on window resize

### ISSUE THREAD

**Issue by bbc2** [ocaml-community/utop#58]
If I launch utop in a terminal and resizes the window, it crashes with the following error:

```
Fatal error: exception Unix.Unix_error(Unix.EINTR, "select", "")
```

I could catch the following with strace in case it might help:

```
select(4, [0 3], [], [], NULL)          = ? ERESTARTNOHAND (To be restarted if no handler)
--- SIGWINCH {si_signo=SIGWINCH, si_code=SI_KERNEL} ---
rt_sigprocmask(SIG_SETMASK, ~[RTMIN RT_1], [WINCH], 8) = 0
write(3, "\1\0\0\0\0\0\0\0", 8)         = 8
rt_sigprocmask(SIG_SETMASK, [WINCH], NULL, 8) = 0
rt_sigreturn()                          = -1 EINTR (Interrupted system call)
(snip)
```

I have utop 1.11 from opam, on Archlinux. My window manager is awesome.

**Comment by jordwalke** [comment]
I see this bug happening when I use a custom `utop` extension (modeled after `m17n`).

**Comment by jvillard** [comment]
This repros consistently on my xterm/Debian too (similar utop as @jordwalke):

```
utop # Fatal error: exception Unix.Unix_error(Unix.EINTR, "select", "")
Raised by primitive operation at unknown location─┬───────┬────────┬──────┬─────┬───────────┬
Called from file "src/unix/lwt_engine.ml", line 371, characters 26-60uffer│Bytes│BytesLabels│
Called from file "src/unix/lwt_engine.ml", line 312, characters 8-39──────┴─────┴───────────┴
Called from file "src/unix/lwt_main.ml", line 41, characters 8-82
Called from file "src/lib/uTop_main.cppo.ml", line 610, characters 4-495
Called from file "src/lib/uTop_main.cppo.ml", line 1319, characters 8-17
Called from file "src/lib/uTop_main.cppo.ml", line 1334, characters 4-15
```

If I'm reading this correctly, then
- `Unix.Unix_error(Unix.EINTR, ...)` is raised by [this call](https://github.com/ocsigen/lwt/blob/c4ac0c4a7ede4a13ee6a87265b7c5d0144286282/src/unix/lwt_engine.ml#L371) to `Unix.select`
- This is itself called inside a `try ... with ...` [here](https://github.com/ocsigen/lwt/blob/c4ac0c4a7ede4a13ee6a87265b7c5d0144286282/src/unix/lwt_engine.ml#L312)
- This `try ... with ...` block catches `Unix.Unix_error(Unix.EINTR, _, _)`!
- So this cannot possibly happen.

**Comment by jordwalke** [comment]
Note that both @jvillard  and I are are using a customized `utop` much like `m17n`.

**Comment by diml** [comment]
OK, can you tell me a bit more about the customized utop, in particular how it is built? One possible error is that the Unix module ends up linked twice. That would explain why the `Unix_error` exception is not caught properly.
