### ISSUE TITLE
Error: The value of the global ... is not yet computed

### ISSUE THREAD

**Issue by johnwhitington** [ocaml-community/utop#95]
I've been trying to build utop top levels with OCamlmakefile based builds, which seems to work fine for my real code.

However, when I tried to produce a minimal example to go into the examples directory of utop, the built top-level doesn't work - when I try to access a value, I get the error in the title of this post:

utop # Code.x;;
Error: The value of the global `Code' is not yet computed             

This is an error from bytecomp/symtable.ml in the OCaml compiler. I'm using utop 1.15 / OCaml 4.02

Here's the code. Just type 'make' and then run './code.top', then try to access Code.x:

http://www.coherentpdf.com/custom-utop-ocamlmakefile.tar.bz2

**Comment by bbatsov** [comment]
@emillon I think this can be closed.
